steps:
  # Step 1: Download and install Terraform
  - name: 'hashicorp/terraform:1.5.3'
    id: 'Install Terraform'
    entrypoint: 'sh'
    args: ['-c', 'terraform version']

  # Step 2: Initialize Terraform
  - name: 'hashicorp/terraform:1.5.3'
    id: 'Terraform Init'
    entrypoint: 'sh'
    args: ['-c', 'terraform init']
    dir: './'  # Directory where your Terraform files are located

  # Step 3: Validate the Terraform configuration
  - name: 'hashicorp/terraform:1.5.3'
    id: 'Terraform Validate'
    entrypoint: 'sh'
    args: ['-c', 'terraform validate']
    dir: './'  # Directory where your Terraform files are located
    waitFor: ['Terraform Init']

  # Step 4: Plan the Terraform deployment with targeting
  - name: 'hashicorp/terraform:1.5.3'
    id: 'Terraform Plan'
    entrypoint: 'sh'
    args: ['-c', 'terraform plan -out=tfplan -target=module.new_resource']
    dir: './'  # Directory where your Terraform files are located
    waitFor: ['Terraform Validate']

  # Step 5: Apply the Terraform configuration (will only create new resources defined in the target)
  - name: 'hashicorp/terraform:1.5.3'
    id: 'Terraform Apply'
    entrypoint: 'sh'
    args: ['-c', 'terraform apply -auto-approve tfplan']
    dir: './'  # Directory where your Terraform files are located
    waitFor: ['Terraform Plan']

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
