apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}  # Use the namespace value from values.yaml
spec:
  replicas: {{ .Values.replicas }}  # Use replicas value from values.yaml
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}  # Image reference from values.yaml
        ports:
        - containerPort: {{ .Values.containerPort }}  # Container port from values.yaml
