apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service  # Name of the service, based on the release name
  namespace: {{ .Values.namespace }}  # Use the namespace value from values.yaml
spec:
  type: LoadBalancer  # Changed from ClusterIP to LoadBalancer for external access
  selector:
    app: {{ .Release.Name }}  # Selector to match the deployment
  ports:
    - port: 80  # Port that the service exposes
      targetPort: {{ .Values.containerPort | default 8081 }}  # Port on the pod that the service will forward to
